export const SET_USER = "SET_USER";
export const USER_LOADING = "USER_LOADING";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_PRODUCT_QUAN = "INCREMENT_PRODUCT_QUAN";
export const DECREMENT_PRODUCT_QUAN = "DECREMENT_PRODUCT_QUAN";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
